### ISSUE TITLE
vscode-abaplint not working 

### ISSUE THREAD

**Issue by codeRSH** [abaplint/vscode-abaplint#100]
Hi, 

I am able to connect to my ABAP system through "ABAP remote filesystem" extension and open a class with "ABAP" extension. 

But the ABAPlint simply doesn't work for me. While performing any action on the code, I am getting following errors . I have been trying since past 2-3 hours but don't understand how to resolve this. Please help or guide me to the relevant link as I am not able to dig it. 

> (node:18608) UnhandledPromiseRejectionWarning: Error: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
>     at checkExecSyncError (child_process.js:630:11)
>     at Object.execSync (child_process.js:666:15)
>     at Object.execSync (electron/js2c/asar.js:727:23)
>     at Function.<anonymous> (c:\Users\Rsinghx0112806\.vscode\extensions\larshp.vscode-abaplint-0.4.183\server\out\server.js:64162:26)
>     at Generator.next (<anonymous>)
>     at c:\Users\Rsinghx0112806\.vscode\extensions\larshp.vscode-abaplint-0.4.183\server\out\server.js:64144:71
>     at new Promise (<anonymous>)
>     at __awaiter (c:\Users\Rsinghx0112806\.vscode\extensions\larshp.vscode-abaplint-0.4.183\server\out\server.js:64140:12)
>     at Function.clone (c:\Users\Rsinghx0112806\.vscode\extensions\larshp.vscode-abaplint-0.4.183\server\out\server.js:64156:16)
>     at Handler.<anonymous> (c:\Users\Rsinghx0112806\.vscode\extensions\larshp.vscode-abaplint-0.4.183\server\out\server.js:9571:59)
> (node:18608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
> [Error - 11:00:40 PM] Request textDocument/hover failed.
>   Message: Request textDocument/hover failed with message: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
>   Code: -32603 
> [Error - 11:00:41 PM] Request textDocument/documentHighlight failed.
>   Message: Request textDocument/documentHighlight failed with message: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
>   Code: -32603 
> [Error - 11:00:41 PM] Request textDocument/codeAction failed.
>   Message: Request textDocument/codeAction failed with message: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
>   Code: -32603 

Regards, 
Ravi

**Comment by larshp** [comment]
does the abaplint extension work standalone? ie. just with files on a normal filesystem?

plus do you have `git` installed? try executing `git` on command line, outside of vscode

**Comment by codeRSH** [comment]
Oops! Git was uninstalled sometime back and I forgot about it. 

Installed git again and it's working fine now. Thanks for the help Lars!

On an unrelated note, is there a setting to turn of the 'linter' part from abaplint and still make use of the features mentioned by you in the blog : https://blogs.sap.com/2020/09/28/standalone-editing-of-abap-in-vscode/

**Comment by larshp** [comment]
abaplint can be configured via the `abaplint.json` file, I'm just not sure if it/how works with the remote file filesystem extension

**Comment by codeRSH** [comment]
Hi Lars, 


It would have git cloned the 'deps' to some location. But I am not able to find the abaplint.json as it created to lint for Remote File System's Objects. I searched through the whole vscode and its settings.

Is there a way to create a custom abaplint.json file somewhere so it doesn't fetch it from internet?

**Comment by larshp** [comment]
if abaplint doesnt find a `abaplint.json` file it uses defaults

I'm not sure if it/how works with the remote file filesystem extension

**Comment by larshp** [comment]
oh, and also see https://github.com/abaplint/vscode-abaplint/issues/69 and https://github.com/abaplint/vscode-abaplint/issues/54

**Comment by codegobbo** [comment]
> does the abaplint extension work standalone? ie. just with files on a normal filesystem?
> 
> plus do you have `git` installed? try executing `git` on command line, outside of vscode

Thank you very much, now it looks good. git was missing on my system. Sorry.
