### ISSUE TITLE
Unhandled promise errors in output

### ISSUE THREAD

**Issue by FreHu** [abaplint/vscode-abaplint#117]
I got a bunch of these when switching branches:
```
(node:4624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 27)
We received a file change event
(node:4624) UnhandledPromiseRejectionWarning: SyntaxError: JSON5: invalid character '<' at 216:1
    at syntaxError (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:59677:17)
    at invalidChar (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:59622:12)
    at Object.value (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:58881:15)
    at lex (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:58672:42)
    at Module.parse (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:58619:17)
    at new Config (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:9937:29)
    at Setup.<anonymous> (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:61566:32)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\i348033\.vscode\extensions\larshp.vscode-abaplint-0.4.298\server\out\server.js:61529:58)
```

suggest adding some generic catch blocks for unexpected situations as these errors always focus the output window

**Comment by FreHu** [comment]
I think it's coming from here:
https://github.com/abaplint/vscode-abaplint/blob/730cf64ebcf4ba5e12cc6cf71e715a05b50fee2d/server/src/handler.ts#L109-L114

**Comment by larshp** [comment]
in the branch switched to, does abaplint.json contain json syntax errors, or non existing?

**Comment by FreHu** [comment]
no, both branches contain a valid file with different contents. i think something gets messed up when git is checking out the files

**Comment by larshp** [comment]
"SyntaxError: JSON5: invalid character '<' at 216:1" it uses the JSON5 parser, so jsonc should be okay

but yea, should add some catch'es
