### ISSUE TITLE
AbAP Cannot read property 'getFilename' of undefined

### ISSUE THREAD

**Issue by mokilok** [abaplint/vscode-abaplint#65]
Hello , 

I got this error at launch.

any idea please?

**TypeError: Cannot read property 'getFilename' of undefined**

```
no custom abaplint config, using defaults
TypeError: Cannot read property 'getFilename' of undefined
    at SyntaxLogic.traverseObject (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:39241:145)
    at SyntaxLogic.run (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:39227:14)
    at CheckSyntax.run (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:39166:51)
    at Registry.runRules (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:42592:45)
    at Registry.findIssuesObject (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:42539:21)
    at Diagnostics.findIssues (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:43581:31)
    at Diagnostics.find (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:43599:29)
    at LanguageServer.diagnostics (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:43186:56)
    at Handler.validateDocument (c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:7627:67)
    at c:\Users\XXXXXX\.vscode\extensions\larshp.vscode-abaplint-0.4.46\server\out\server.js:185:13
[Error - 11:20:49] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'getFilename' of undefined
  Code: -32603 
[Error - 11:20:49] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'getFilename' of undefined
  Code: -32603 
```

**Comment by larshp** [comment]
looks like a bug

as a temporary workaround, try creating a default `abaplint.json` file, and disable the `check_syntax` rule

**Comment by larshp** [comment]
ref https://github.com/abaplint/abaplint/blob/7513aa31bdef4aab0d3bf36c6041f3233d749c90/packages/core/src/abap/5_syntax/syntax.ts#L94

its a program/PROG object where the main file cannot be found

**Comment by mokilok** [comment]
Hello , larshp, 
First of all thanks for all your work . 

i don't know where to put the abaplint.json file .

i'am using th ABAP remote filesystem

**Comment by larshp** [comment]
oh, then you have to await the fix, will do it later today

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/commit/0f8141dd6ceb463e537051b68b74541a68bd316b should solve this, however I could not reproduce the issue

**Comment by mokilok** [comment]
Thanks a lot . 

will wait the next release and let you know.

**Comment by larshp** [comment]
try again, v0.4.48 released, will appear in a few minutes

**Comment by mokilok** [comment]
Perfectly working thanks .

i am not used to this kind of fast fix ( SAP support lol)

**Comment by larshp** [comment]
and thanks for the bug report 👍
